# Generated by Django 4.0.6 on 2022-08-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortality_classification_entry',
            name='bicarbonate',
            field=models.FloatField(null=True),
        ),
    ]
